https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html

In [1]:
import torch
import numpy as np

In [2]:
torch.__version__

'1.9.0+cu102'

In [3]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)


In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [5]:
x_data

tensor([[1, 2],
        [3, 4]])

In [6]:
x_np

tensor([[1, 2],
        [3, 4]])

In [7]:
np_array

array([[1, 2],
       [3, 4]])

In [17]:
x_ones = torch.ones_like(x_data,) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.3358, 0.6770],
        [0.0893, 0.7615]]) 



In [18]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.8444, 0.9344, 0.1335],
        [0.7511, 0.3538, 0.1644]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [19]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [20]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

In [22]:
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [24]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print('First row: ',tensor[0])
print('First column: ', tensor[:, 1])
print('Last column:', tensor[..., -1])

print(tensor)

First row:  tensor([1., 0., 1., 1.])
First column:  tensor([0., 0., 0., 0.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [30]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [40]:
tensor[:, 0] = 2

In [41]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[4., 0., 1., 1.],
        [4., 0., 1., 1.],
        [4., 0., 1., 1.],
        [4., 0., 1., 1.]])

In [43]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

16.0 <class 'float'>


In [45]:
tensor

tensor([[2., 0., 1., 1.],
        [2., 0., 1., 1.],
        [2., 0., 1., 1.],
        [2., 0., 1., 1.]])

In [46]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[2., 0., 1., 1.],
        [2., 0., 1., 1.],
        [2., 0., 1., 1.],
        [2., 0., 1., 1.]]) 

tensor([[7., 5., 6., 6.],
        [7., 5., 6., 6.],
        [7., 5., 6., 6.],
        [7., 5., 6., 6.]])


In [42]:
z2

tensor([[4., 0., 1., 1.],
        [4., 0., 1., 1.],
        [4., 0., 1., 1.],
        [4., 0., 1., 1.]])

In [35]:
tensor.matmul(tensor.T)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [32]:
y2

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [48]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [49]:
type(n)

numpy.ndarray

In [50]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [51]:
n = np.ones(5)
t = torch.from_numpy(n)

In [54]:
np.add(n,1, out = n)

array([2., 2., 2., 2., 2.])

In [55]:
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
